### ISSUE TITLE
LICENSE? is it ISC, MIT or Apache?

### ISSUE THREAD

**Issue by rudolfolah** [martinmyrvoll/ChatGPT-autogenerated-quiz-app#2]
Hi, I noticed that the `package.json` has ISC however there isn't a LICENSE file.

There's a template for ISC here: https://opensource.org/license/isc-license-txt/

and a template for MIT here: https://opensource.org/license/mit/

**Comment by martinmyrvoll** [comment]
Thanks for pointing it out!
Fixed it now, it's MIT.
